name: v2
description: Tele Cinema - تطبيق مشاهدة الأفلام

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 🌐 الاتصال بالإنترنت
  dio: ^5.4.0

  # 💾 التخزين المحلي
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # 🖼️ الصور
  cached_network_image: ^3.3.0

  # 🎬 مشغل الفيديو
  video_player: ^2.8.0

  # 🔋 منع الشاشة من الإغلاق
  wakelock_plus: ^1.1.0

  # 📶 فحص الاتصال بالإنترنت
  connectivity_plus: ^5.0.0

  # 📁 الوصول للملفات
  path_provider: ^2.1.0

  # 🔤 النصوص
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/iconic.png

  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
        - asset: fonts/Cairo-Bold.ttf
          weight: 700
