dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  cached_network_image: ^3.3.0
  video_player: ^2.8.1
  chewie: ^1.7.4
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.13.6
  
