import 'package:flutter/material.dart';
import 'core.dart';

/* ======== الترجمة ======== */
class Lang {
  static final ValueNotifier<String> locale = ValueNotifier('ar');
  static String get lang => locale.value;
  static void set(String v) => locale.value = v;
  static String t(String k) => (lang == 'en' ? _en : _ar)[k] ?? _ar[k] ?? k;
}

/* ======== الثيمات ======== */
class AppTheme {
  static const Map<String, int> _colors = {
    'gold': 0xFFE5B13D,
    'blue': 0xFF0088CC,
    'green': 0xFF4CAF50,
    'purple': 0xFF9C57FF,
    'red': 0xFFE53935,
  };
  static Color get accent => Color(_colors[Store.theme] ?? 0xFFE5B13D);
  static ThemeData build(String name) {
    final c = Color(_colors[name] ?? 0xFFE5B13D);
    return ThemeData(
      brightness: Brightness.dark,
      useMaterial3: true,
      colorScheme: ColorScheme.dark(
          primary: c, secondary: c, surface: const Color(0xFF0B0F14)),
      scaffoldBackgroundColor: const Color(0xFF0B0F14),
      navigationBarTheme: NavigationBarThemeData(
          backgroundColor: const Color(0xFF12161F), indicatorColor: c),
      appBarTheme:
          const AppBarTheme(backgroundColor: Color(0xFF12161F), centerTitle: true),
      cardTheme: const CardTheme(color: Color(0xFF151B23)),
    );
  }
}

const _ar = {
  'appName': 'تلي سينما',
  'movies': 'الأفلام',
  'favorites': 'المفضلة',
  'watched': 'شاهدتها',
  'downloads': 'تحميلاتي',
  'channels': 'القنوات',
  'settings': 'الإعدادات',
  'searchHint': 'ابحث عن فيلم…',
  'noMovies': 'لا توجد أفلام بعد — أضف قناة من تبويب القنوات',
  'noFav': 'لا توجد أفلام مفضلة بعد',
  'noFavHint': 'اضغط على القلب ❤️ في أي فيلم لإضافته هنا',
  'noHistory': 'لا يوجد سجل مشاهدة بعد',
  'noDownloads': 'لا توجد تحميلات',
  'addChannelHint': 'الصق رابط القناة أو @اليوزر…',
  'addChannel': 'إضافة قناة',
  'noChannels': 'لا توجد قنوات بعد',
  'noChannelsHint': 'أضف قناة أفلام من تيليجرام وستظهر جميع فيديوهاتها هنا',
  'allChannels': 'الكل — جميع القنوات',
  'channelNoMovies': 'لم يتم العثور على أفلام في هذه القناة',
  'serverFail': 'تعذر الاتصال بالخادم — تأكد أن البوت يعمل',
  'language': 'اللغة',
  'arabic': 'العربية',
  'english': 'English',
  'appearance': 'المظهر',
  'themeGold': 'ذهبي',
  'themeBlue': 'أزرق',
  'themeGreen': 'أخضر',
  'themePurple': 'بنفسجي',
  'themeRed': 'أحمر',
  'viewMode': 'طريقة العرض',
  'grid': 'شبكة',
  'list': 'قائمة',
  'hideWatched': 'إخفاء المُشاهد',
  'incognito': 'وضع التخفي',
  'incognitoHint': 'لا يحفظ سجل المشاهدة',
  'wifiOnly': 'التحميل على WiFi فقط',
  'wifiNeeded': 'التحميل متاح على WiFi فقط — فعّل من الإعدادات أو اتصل بشبكة WiFi',
  'kidsMode': 'وضع الأطفال',
  'kidsModeHint': 'يعرض المحتوى العائلي فقط',
  'storage': 'التخزين',
  'clearCache': 'تنظيف كاش السيرفر',
  'cacheCleared': 'تم التنظيف ✅',
  'play': 'تشغيل',
  'download': 'تحميل',
  'pause': 'إيقاف مؤقت',
  'resume': 'استئناف',
  'cancel': 'إلغاء',
  'completed': 'المكتملة',
  'downloading': 'جاري التحميل…',
  'pausedDl': 'متوقف مؤقتاً',
  'startedDl': 'بدأ التحميل — تابعه في تبويب تحميلاتي',
  'failedPlay': 'تعذر تشغيل الفيديو — تحقق من الاتصال',
  'speed': 'السرعة',
  'playerLock': 'قفل',
  'playerUnlock': 'فك القفل',
  'sleepTimer': 'مؤقت النوم',
  'off': 'إيقاف',
  'skipIntro': 'تخطي المقدمة',
  'nextMovie': 'التالي',
  'audioOnly': 'صوت فقط',
  'continueWatching': 'أكمل المشاهدة',
  'watchLater': 'سأشاهده لاحقاً',
  'playlists': 'قوائمي',
  'newPlaylist': 'قائمة جديدة',
  'trailer': 'الإعلان',
  'mostWatched': 'الأكثر مشاهدة',
  'randomPick': 'فيلم عشوائي',
  'todayPick': 'اختيار اليوم',
  'similar': 'أفلام مشابهة',
  'stats': 'إحصائياتي',
  'hoursWatched': 'ساعة مشاهدة',
  'moviesWatched': 'فيلم شاهدته',
  'achievements': 'الإنجازات',
  'quality': 'الجودة',
  'genre': 'النوع',
  'all': 'الكل',
  'delete': 'حذف',
  'close': 'إغلاق',
  'retry': 'إعادة المحاولة',
  'backup': 'نسخ احتياطي',
  'exportData': 'تصدير البيانات',
  'importData': 'استيراد البيانات',
  'newMovies': 'أفلام جديدة وصلت!',
};

const _en = {
  'appName': 'Tele Cinema',
  'movies': 'Movies',
  'favorites': 'Favorites',
  'watched': 'Watched',
  'downloads': 'Downloads',
  'channels': 'Channels',
  'settings': 'Settings',
  'searchHint': 'Search movies…',
  'noMovies': 'No movies yet — add a channel from the Channels tab',
  'noFav': 'No favorites yet',
  'noFavHint': 'Tap the ❤️ on any movie to add it here',
  'noHistory': 'No watch history yet',
  'noDownloads': 'No downloads',
  'addChannelHint': 'Paste channel link or @username…',
  'addChannel': 'Add channel',
  'noChannels': 'No channels yet',
  'noChannelsHint': 'Add a Telegram movie channel and all its videos will appear here',
  'allChannels': 'All — every channel',
  'channelNoMovies': 'No movies found in this channel',
  'serverFail': 'Cannot reach server — make sure the bot is running',
  'language': 'Language',
  'arabic': 'العربية',
  'english': 'English',
  'appearance': 'Appearance',
  'themeGold': 'Gold',
  'themeBlue': 'Blue',
  'themeGreen': 'Green',
  'themePurple': 'Purple',
  'themeRed': 'Red',
  'viewMode': 'View mode',
  'grid': 'Grid',
  'list': 'List',
  'hideWatched': 'Hide watched',
  'incognito': 'Incognito mode',
  'incognitoHint': 'Do not save watch history',
  'wifiOnly': 'Download on WiFi only',
  'wifiNeeded': 'Downloads allowed on WiFi only — change in Settings or connect to WiFi',
  'kidsMode': 'Kids mode',
  'kidsModeHint': 'Show family content only',
  'storage': 'Storage',
  'clearCache': 'Clear server cache',
  'cacheCleared': 'Cleared ✅',
  'play': 'Play',
  'download': 'Download',
  'pause': 'Pause',
  'resume': 'Resume',
  'cancel': 'Cancel',
  'completed': 'Completed',
  'downloading': 'Downloading…',
  'pausedDl': 'Paused',
  'startedDl': 'Download started — follow it in Downloads tab',
  'failedPlay': 'Cannot play video — check connection',
  'speed': 'Speed',
  'playerLock': 'Lock',
  'playerUnlock': 'Unlock',
  'sleepTimer': 'Sleep timer',
  'off': 'Off',
  'skipIntro': 'Skip intro',
  'nextMovie': 'Next',
  'audioOnly': 'Audio only',
  'continueWatching': 'Continue Watching',
  'watchLater': 'Watch Later',
  'playlists': 'My Lists',
  'newPlaylist': 'New list',
  'trailer': 'Trailer',
  'mostWatched': 'Most Watched',
  'randomPick': 'Random movie',
  'todayPick': "Today's Pick",
  'similar': 'Similar movies',
  'stats': 'My Stats',
  'hoursWatched': 'hours watched',
  'moviesWatched': 'movies watched',
  'achievements': 'Achievements',
  'quality': 'Quality',
  'genre': 'Genre',
  'all': 'All',
  'delete': 'Delete',
  'close': 'Close',
  'retry': 'Retry',
  'backup': 'Backup',
  'exportData': 'Export data',
  'importData': 'Import data',
  'newMovies': 'New movies arrived!',
};
